#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-typing_extensions
Version  : 4.1.1
Release  : 39
URL      : https://files.pythonhosted.org/packages/b1/5a/8b5fbb891ef3f81fc923bf3cb4a578c0abf9471eb50ce0f51c74212182ab/typing_extensions-4.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/b1/5a/8b5fbb891ef3f81fc923bf3cb4a578c0abf9471eb50ce0f51c74212182ab/typing_extensions-4.1.1.tar.gz
Summary  : Backported and Experimental Type Hints for Python 3.6+
Group    : Development/Tools
License  : Python-2.0
Requires: pypi-typing_extensions-license = %{version}-%{release}
Requires: pypi-typing_extensions-python = %{version}-%{release}
Requires: pypi-typing_extensions-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)

%description
No detailed description available

%package license
Summary: license components for the pypi-typing_extensions package.
Group: Default

%description license
license components for the pypi-typing_extensions package.


%package python
Summary: python components for the pypi-typing_extensions package.
Group: Default
Requires: pypi-typing_extensions-python3 = %{version}-%{release}

%description python
python components for the pypi-typing_extensions package.


%package python3
Summary: python3 components for the pypi-typing_extensions package.
Group: Default
Requires: python3-core
Provides: pypi(typing_extensions)

%description python3
python3 components for the pypi-typing_extensions package.


%prep
%setup -q -n typing_extensions-4.1.1
cd %{_builddir}/typing_extensions-4.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644864272
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-typing_extensions
cp %{_builddir}/typing_extensions-4.1.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-typing_extensions/7ad627868f90ad068bd06801aab97ec1ca34b890
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-typing_extensions/7ad627868f90ad068bd06801aab97ec1ca34b890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
